lane :pods do
	cocoapods(podfile: "Example/")
end

lane :tests do
	pods
	scan(workspace: "Example/Trakt.xcworkspace", scheme: "Trakt-Example", clean: true, devices: ["iPhone 5"])
end

desc "Run all tests and linters"
lane :lint do
	tests
	pod_lib_lint(allow_warnings: false, verbose: false)
	slather(cobertura_xml: true, travis: true, scheme: "Trakt-Example", build_directory: "Example/Build", output_directory: "./reports", proj: "Example/Trakt.xcodeproj", workspace: "Example/Trakt.xcworkspace")
    sh("cd .. && lizard ./Example -l swift --xml > ./reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
end

desc "Run all tests and linters then upload metrics to sonar"
lane :upload_sonar do
	lint
	sonar(sonar_login: ENV["SONAR_LOGIN"])
end